name = "email-worker"
main = "src/worker.ts"
compatibility_date = "2023-06-26"

send_email = [
    {type = "send_email", name = "send_emails", destination_address = "codebam@riseup.net"},
]

kv_namespaces = [
	{ binding = "email_reminders", id = "7a54dc75c2ea4ead9476e43027881b74" }
]

[triggers]
crons = ["0 8 * * *"]
